import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import MainNavigation from "@/app/ui/navigation/main-navigation";
import Hamburger from "@/app/ui/navigation/hamburger";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased static`}
            >
                <header className="bg-zinc-800 opacity-80 flex flex-row justify-between absolute top-0 left-0 w-full">
                    <h1 className="m-4 ms-8 lg:ms-16 text-red-600 font-semibold text-2xl lg:font-bold lg:text-3xl hover:animate-pulse cursor-pointer">
                        <em>Next Cars</em>
                    </h1>
                    <MainNavigation />
                    <Hamburger />
                </header>
                <main className="flex flex-col items-center p-16">{children}</main>
                <footer className="bg-zinc-800 opacity-80 flex flex-row align-middle justify-center absolute bottom-0 left-0 w-full">
                    <Link
                        href="https://mihais-git.github.io/"
                        className="text-zinc-50 my-4"
                    >
                        Mihai Suciu &copy; 2025
                    </Link>
                </footer>
            </body>
        </html>
    );
}
